### ISSUE TITLE
Hesaba para gelmiyor.

### ISSUE THREAD

**Issue by BR1907** [bynonper00/esx_hackerjob#1]
Kredi kartini cal dedikten sonra basarili hacklemede hesabiniza para aktarildi yazisi cikmasina ragmen ne banka ne de nakit olarak hesaba para gelmiyor. Ama ekranda gta v in kendi bank +758 yazisi cikiyor.

**Comment by getrepos** [comment]
Kullandığınız banka scriptine göre kendiniz düzenlemelisiniz.
